In [22]:
import sys
sys.path.append("..")

import torch

%load_ext autoreload
%autoreload 2
from src.pooling import TemporalAttentionPooling, \
                        TemporalAvgPooling, \
                        TemporalLastPooling, \
                        TemporalMaxPooling

In [19]:
x = torch.rand((2, 5, 2))
x

tensor([[[0.5474, 0.0218],
         [0.0231, 0.4857],
         [0.0553, 0.4392],
         [0.1272, 0.7596],
         [0.6558, 0.6279]],

        [[0.6087, 0.7518],
         [0.2296, 0.1966],
         [0.3800, 0.0740],
         [0.0797, 0.0792],
         [0.6863, 0.0611]]])

In [102]:
mask_a = torch.LongTensor([[1, 1, 1, 1, 0], 
                           [1, 1, 1, 0, 0]])
mask_a.shape

torch.Size([2, 5])

In [103]:
last_pooling = TemporalLastPooling()
last_pooling(x, mask_a)

tensor([[0.1272, 0.7596],
        [0.3800, 0.0740]])

In [104]:
max_pooling = TemporalMaxPooling()
max_pooling(x, mask_a).shape

torch.Size([2, 2])

In [105]:
avg_pooling = TemporalAvgPooling()
avg_pooling(x, mask_a)

tensor([[0.1882, 0.4266],
        [0.4061, 0.3408]])

In [107]:
attn_pooling = TemporalAttentionPooling(2)
attn_pooling(x, mask_a)

tensor([[0.7530, 1.7063],
        [1.2183, 1.0225]], grad_fn=<SqueezeBackward1>)